//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinCopies.GUI.IO.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinCopies.GUI.IO.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copies the name of the selected item..
        /// </summary>
        public static string CopyNameStatusBarLabel {
            get {
                return ResourceManager.GetString("CopyNameStatusBarLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copies the path of the selected item..
        /// </summary>
        public static string CopyPathStatusBarLabel {
            get {
                return ResourceManager.GetString("CopyPathStatusBarLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination path:.
        /// </summary>
        public static string DestinationPath {
            get {
                return ResourceManager.GetString("DestinationPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory structure.
        /// </summary>
        public static string DirectoryStructure {
            get {
                return ResourceManager.GetString("DirectoryStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include empty directories.
        /// </summary>
        public static string IncludeEmptyDirectories {
            get {
                return ResourceManager.GetString("IncludeEmptyDirectories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item could not be created..
        /// </summary>
        public static string ItemCouldNotBeCreated {
            get {
                return ResourceManager.GetString("ItemCouldNotBeCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item could not be renamed..
        /// </summary>
        public static string ItemCouldNotBeRenamed {
            get {
                return ResourceManager.GetString("ItemCouldNotBeRenamed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item creation error.
        /// </summary>
        public static string ItemCreationError {
            get {
                return ResourceManager.GetString("ItemCreationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item rename error.
        /// </summary>
        public static string ItemRenameError {
            get {
                return ResourceManager.GetString("ItemRenameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens a dialog for item creation..
        /// </summary>
        public static string NewItemCommandToolTip {
            get {
                return ResourceManager.GetString("NewItemCommandToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens the selected item in a new tab..
        /// </summary>
        public static string OpenInNewTabStatusBarLabel {
            get {
                return ResourceManager.GetString("OpenInNewTabStatusBarLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens the selected item in a new window..
        /// </summary>
        public static string OpenInNewWindowStatusBarLabel {
            get {
                return ResourceManager.GetString("OpenInNewWindowStatusBarLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens the selected items..
        /// </summary>
        public static string OpenOrLaunchStatusBarLabel {
            get {
                return ResourceManager.GetString("OpenOrLaunchStatusBarLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preserve directory root.
        /// </summary>
        public static string PreserveDirectoryRoot {
            get {
                return ResourceManager.GetString("PreserveDirectoryRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Quit.
        /// </summary>
        public static string Quit {
            get {
                return ResourceManager.GetString("Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closes all windows of the current process..
        /// </summary>
        public static string QuitStatusBarLabel {
            get {
                return ResourceManager.GetString("QuitStatusBarLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens a dialog for item renaming..
        /// </summary>
        public static string RenameItemCommandToolTip {
            get {
                return ResourceManager.GetString("RenameItemCommandToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit a _bug....
        /// </summary>
        public static string SubmitABug {
            get {
                return ResourceManager.GetString("SubmitABug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens your default browser at the WinCopies&apos; GitHub page..
        /// </summary>
        public static string SubmitABugStatusBarLabel {
            get {
                return ResourceManager.GetString("SubmitABugStatusBarLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have multiple tabs open. Are you sure you want to close the window?.
        /// </summary>
        public static string WindowClosingMessage {
            get {
                return ResourceManager.GetString("WindowClosingMessage", resourceCulture);
            }
        }
    }
}
