//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinCopies.IO.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinCopies.IO.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compression.
        /// </summary>
        public static string Compression {
            get {
                return ResourceManager.GetString("Compression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .Net Attribute.
        /// </summary>
        public static string DotNetAttribute {
            get {
                return ResourceManager.GetString("DotNetAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .Net Member.
        /// </summary>
        public static string DotNetMember {
            get {
                return ResourceManager.GetString("DotNetMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .Net Namespace.
        /// </summary>
        public static string DotNetNamespace {
            get {
                return ResourceManager.GetString("DotNetNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .Net Parameter.
        /// </summary>
        public static string DotNetParameter {
            get {
                return ResourceManager.GetString("DotNetParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .Net Type.
        /// </summary>
        public static string DotNetType {
            get {
                return ResourceManager.GetString("DotNetType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extraction.
        /// </summary>
        public static string Extraction {
            get {
                return ResourceManager.GetString("Extraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portable Device.
        /// </summary>
        public static string PortableDevice {
            get {
                return ResourceManager.GetString("PortableDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registry Key.
        /// </summary>
        public static string RegistryKey {
            get {
                return ResourceManager.GetString("RegistryKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registry Root.
        /// </summary>
        public static string RegistryRoot {
            get {
                return ResourceManager.GetString("RegistryRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registry Value.
        /// </summary>
        public static string RegistryValue {
            get {
                return ResourceManager.GetString("RegistryValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WMI Class.
        /// </summary>
        public static string WMIClass {
            get {
                return ResourceManager.GetString("WMIClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WMI Instance.
        /// </summary>
        public static string WMIInstance {
            get {
                return ResourceManager.GetString("WMIInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WMI Namespace.
        /// </summary>
        public static string WMINamespace {
            get {
                return ResourceManager.GetString("WMINamespace", resourceCulture);
            }
        }
    }
}
